In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
from kaggle_projects.home_credit_default_risk.utils import get_app_bureau_dataset, get_prev_app_dataset

# Application EDA

Goal: Can you predict how capable each applicant is of repaying a loan?

## Data Schema
<img src="home_credit_data_schema.png">

In [4]:
%%time
app_df = get_app_bureau_dataset(test=False)
app_df

Loading application dataset - test:  False
Merging Credit Bureau data...
CPU times: user 15 s, sys: 12.4 s, total: 27.5 s
Wall time: 34.7 s

          SK_ID_CURR  TARGET  ... MONTHS_BALANCE STATUS
0             100002       1  ...          -15.0      C
1             100002       1  ...          -16.0      C
2             100002       1  ...          -17.0      0
3             100002       1  ...          -18.0      0
4             100002       1  ...          -19.0      0
...              ...     ...  ...            ...    ...
15687437      456255       0  ...          -72.0      C
15687438      456255       0  ...          -73.0      C
15687439      456255       0  ...          -74.0      C
15687440      456255       0  ...          -75.0      0
15687441      456255       0  ...          -76.0      X

[15687442 rows x 140 columns]

In [ ]:
%%time
prev_app_df = get_prev_app_dataset()
prev_app_df

Merging previous application data...